### ISSUE TITLE
Intention?

### ISSUE THREAD

**Issue by ajs6f** [fcrepo4-labs/fcrepo-vocabulary#1]
Is the idea to strengthen this until we can shift the other code bases onto it?

**Comment by acoburn** [comment]
Yes, that's pretty much the idea. We should be able to replace the hodge-podge that is RdfLexicon with this. Other projects may also find it useful.

The idea is that it could be versioned independently.

**Comment by acoburn** [comment]
This is also built on CommonsRDF (v0.2), and I wouldn't want other projects to start using it until v0.3 is out. That's when the improved Jena support will be present.

**Comment by ajs6f** [comment]
Excellent... {steeples fingers}
